using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using Valve.VR;

public class InputTest : MonoBehaviour
{
    // a reference to the action
    public SteamVR_Action_Boolean fire;
    // a reference to the hand
    public SteamVR_Input_Sources handType;
    public void Awake()
    {

        fire.AddOnStateDownListener(OnFireL, handType);
    }

    public void Update()
    {
        //for (int i = 0; i < 10000000; i++)
        //{

        //}
    }
    public void OnFireL(SteamVR_Action_Boolean fromAction, SteamVR_Input_Sources fromSource)
    {
        Debug.Log(string.Format("current: {0}\t input: {1}\t rotation:{2}", fromAction.changedTime, Time.time, 0));
    }

    public void OnFireR(InputAction.CallbackContext context)
    {

    }
}
